### ISSUE TITLE
Building with Meson fails

### ISSUE THREAD

**Issue by FelixEickeler** [lua-batteries/lua-batteries#2]
I am trying to build lua-batteries with VS2015 on Windows 11. The following error occurs when executing the meson setup:

![image](https://github.com/lua-batteries/lua-batteries/assets/25435516/7cb2f97f-81c3-4f50-9862-9a3e9d18d350)

I cannot make any additonal information from the log file.

**Comment by clitic** [comment]
Make sure you have windows resource compiler (rc) installed properly.

**Comment by FelixEickeler** [comment]
Thank you for your answer and the great work.

For people that hit the same roadblock, for the clean install of VS2015 today (12/2023). The rc is installed with the SDKs "C:\Program Files (x86)\Windows Kits\10\bin\1x.x.xxxxx.x\x64"  and as for me was not added to path, and is not described in the meson setup. 

However, additonally c++17 is defined as requrired in 3 suboprojects that needs to be changed (toml, magic_enum and tomlplusplus). I did not follow though with the compile, due to the advanced requriemets as I mostly need lua and a single package.
